# Generated by Django 4.0.2 on 2022-02-24 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200914_1537'),
        ('blog', '0002_initial'),
    ]

    operations = [
    ]
